This a makey-upey neural network with 1 layer of 5 neurons which is the output layer.
Each input has 4 values and is associated with desired output with 5 values. All this requires a 5 by 4 weight matrix.
16 sample inputs and corresponding desired outputs are provided.

Yout task is to write code for feedforward() and getCost().

Then you are finally asked to add another layer to the network.

In [28]:
import numpy as np

# Sigmoid activation function
def sigm(z):
    return 1.0 / (1.0 + np.exp(-z))  # Sigmoid function: Maps any input to a value between 0 and 1

In [29]:
# Input data (16 samples with 4 values each)
inputs = np.array([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],
                   [0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],
                   [1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],
                   [1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]])

# Desired output (5 values per input)
targets = np.array([[1,0,0,0,0],[1,0,0,0,0],[0,1,0,0,0],[0,1,0,0,0],
                    [0,0,1,0,0],[0,0,1,0,0],[0,1,0,0,0],[0,0,1,0,0],
                    [0,0,1,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,1,0],
                    [0,0,0,0,1],[0,0,0,1,0],[0,0,1,0,0],[0,1,0,0,0]])

print(inputs, '\n')
print(inputs.shape, '\n')
print(targets, '\n')
print(targets.shape)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]] 

(16, 4) 

[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]] 

(16, 5)


In [30]:
# Neural Network with 4 inputs and 5 outputs (one hidden layer)
class NN(object):
    def __init__(self):
        np.random.seed(2021)  # Seed for reproducibility
        self.w = np.random.randn(5, 4)  # Weights matrix with 5 rows and 4 cols (4 inputs, 5 neurons)
        self.b = np.random.randn(5, 1)  # 5-item column vector containing biases for the output layer
    
    def feedforward(self, x):
        # Input layer to output layer
        z_hidden = np.dot(self.w, x.reshape(4, 1)) + self.b  # Weighted sum of inputs + biases
        a_hidden = sigm(z_hidden)  # Apply sigmoid activation function
        return a_hidden  # Return output of the layer
    
    def getCost(self, xs, ys):
        cost = 0.0
        # Loop through each sample in the dataset
        for i in range(len(xs)):
            x = xs[i].reshape(4, 1)  # Reshape input to column vector (4, 1)
            y = ys[i].reshape(5, 1)  # Reshape target to column vector (5, 1)

            # Forward pass
            a_hidden = self.feedforward(x)

            # Calculate cost using Mean Squared Error (MSE)
            cost += np.sum((a_hidden - y) ** 2)
        
        return cost / 16.0  # Return average MSE cost over all 16 samples

In [31]:
# Create the neural network and check weights and biases
nn = NN()
print(nn.w, '\n')
print(nn.b)

[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]
 [ 0.10641374  0.42215483  0.12420684 -0.83795346]
 [ 0.4090157   0.10275122 -1.90772239  1.1002243 ]
 [-1.40232506 -0.22508127 -1.33620597  0.30372151]] 

[[-0.72015884]
 [ 2.5449146 ]
 [ 1.31729112]
 [ 0.0726303 ]
 [-0.25610814]]


In [32]:
# Test feedforward on first input vector
# The input vector (shape 4,) must first be reshaped to a column vector (shape 4,1)
print(nn.feedforward(inputs[0].reshape(4, 1)))

[[0.32735801]
 [0.92723113]
 [0.78873067]
 [0.5181496 ]
 [0.43632065]]


In [33]:
# Compute average MSE cost over all input vectors
print(nn.getCost(inputs, targets))

1.7771013151641077


Exercise: Copy the above NN class definition and pasted it to a new cell, renaming the class to NN2. Then add a layer of six hidden neurons to it. Modify code in NN2 so that feedforward() and getCost() work on this new architecture. 

In [34]:
# Neural Network with 4 inputs, 5 outputs, and two hidden layers
class NN2(object):
    def __init__(self):
        np.random.seed(2021)  # Seed for reproducibility
        # Initialize weights and biases for the two layers
        self.w1 = np.random.randn(5, 4)  # Weights matrix for the first hidden layer (5 neurons, 4 inputs)
        self.b1 = np.random.randn(5, 1)  # Biases for the first hidden layer (5 biases)
        
        self.w2 = np.random.randn(5, 5)  # Weights matrix for the second hidden layer (5 neurons, 5 neurons from layer 1)
        self.b2 = np.random.randn(5, 1)  # Biases for the second hidden layer (5 biases)

    def feedforward(self, x):
        # Input layer to hidden layer 1
        z_hidden1 = np.dot(self.w1, x.reshape(4, 1)) + self.b1  # Weighted sum for layer 1
        a_hidden1 = sigm(z_hidden1)  # Apply sigmoid activation for layer 1
        
        # Hidden layer 1 to hidden layer 2
        z_hidden2 = np.dot(self.w2, a_hidden1) + self.b2  # Weighted sum for layer 2
        a_hidden2 = sigm(z_hidden2)  # Apply sigmoid activation for layer 2

        # Return output of second hidden layer (final activations for now)
        return a_hidden2
    
    def getCost(self, xs, ys):
        cost = 0.0
        # Loop through each sample in the dataset
        for i in range(len(xs)):
            x = xs[i].reshape(4, 1)  # Reshape input to column vector (4, 1)
            y = ys[i].reshape(5, 1)  # Reshape target to column vector (5, 1)

            # Forward pass
            a_hidden = self.feedforward(x)

            # Calculate cost using Mean Squared Error (MSE)
            cost += np.sum((a_hidden - y) ** 2)
        
        return cost / 16.0  # Return average MSE cost over all 16 samples

In [35]:
# Create NN2 (two hidden layers) and check feedforward and cost calculation
nn2 = NN2()
print(nn2.w1, '\n')
print(nn2.b1)
print(nn2.w2, '\n')
print(nn2.b2)

[[ 1.48860905  0.67601087 -0.41845137 -0.80652081]
 [ 0.55587583 -0.70550429  1.13085826  0.64500184]
 [ 0.10641374  0.42215483  0.12420684 -0.83795346]
 [ 0.4090157   0.10275122 -1.90772239  1.1002243 ]
 [-1.40232506 -0.22508127 -1.33620597  0.30372151]] 

[[-0.72015884]
 [ 2.5449146 ]
 [ 1.31729112]
 [ 0.0726303 ]
 [-0.25610814]]
[[ 0.13801041  1.14723599  1.37626076 -0.47218397  0.5240849 ]
 [ 1.48510793  1.48243225  0.72813051 -0.38964808  0.27889376]
 [ 0.0519002  -1.04474368 -0.16150753 -2.79353057  0.36164801]
 [ 0.24010758  0.47781228  0.20885194  0.91791163 -1.41177784]
 [ 1.22423572 -0.54565772  0.90674805 -0.98261724 -0.63316189]] 

[[ 0.82552024]
 [-1.28449686]
 [-0.34730878]
 [-1.07776075]
 [ 0.97257495]]


In [36]:
# Test feedforward on a new input vector
print(nn2.feedforward(np.array([1, 1, 0, 1]).reshape(4, 1)))

# Compute average MSE cost over all input vectors
print(nn2.getCost(inputs, targets))

[[0.93762534]
 [0.79484326]
 [0.02358345]
 [0.55513918]
 [0.72712863]]
2.3073609747898476
